export const QUESTIONSET_FETCH_ALL = 'QUESTIONSET_FETCH_ALL';
export const QUESTIONSET_FETCH_SINGLE = "QUESTIONSET_FETCH_SINGLE";
export const QUESTIONSET_FETCH_LOADING = 'QUESTIONSET_FETCH_LOADING';
export const QUESTIONSET_FETCH_ERROR = 'QUESTIONSET_FETCH_ERROR';
export const QUESTIONSET_FETCH_MESSAGE = 'QUESTIONSET_FETCH_MESSAGE';
export const QUESTIONSET_CLEAR_STATE = 'QUESTIONSET_CLEAR_STATE';