export const ImgLogo = require('../Assets/images/Logo.png')
export const ImgFeatured = require('../Assets/images/Featured.png')

export const UserIcon = require('../Assets/icons/userIcon.png')
export const PwIcon = require('../Assets/icons/pwIcon.png')
export const AgeIcon = require('../Assets/icons/ageIcon.png')
export const EmailIcon = require('../Assets/icons/emailIcon.png')
export const NicIcon = require('../Assets/icons/nicIcon.png')
export const PhoneIcon = require('../Assets/icons/phoneIcon.png')
export const ImgIcon = require('../Assets/icons/imgIcon.png')
export const CameraIcon = require('../Assets/icons/cameraIcon.png')
export const GalleryIcon = require('../Assets/icons/galleryIcon.png')