export const CAREA_FETCH_ALL = 'CAREA_FETCH_ALL';
export const CAREA_FETCH_SINGLE = "CAREA_FETCH_SINGLE";
export const CAREA_FETCH_LOADING = 'CAREA_FETCH_LOADING';
export const CAREA_FETCH_ERROR = 'CAREA_FETCH_ERROR';
export const CAREA_FETCH_MESSAGE = 'CAREA_FETCH_MESSAGE';
export const CAREA_CLEAR_STATE = 'CAREA_CLEAR_STATE';