export const RECOMMENDATION_FETCH_ALL = 'RECOMMENDATION_FETCH_ALL';
export const RECOMMENDATION_FETCH_SINGLE = "RECOMMENDATION_FETCH_SINGLE";
export const RECOMMENDATION_FETCH_LOADING = 'RECOMMENDATION_FETCH_LOADING';
export const RECOMMENDATION_FETCH_ERROR = 'RECOMMENDATION_FETCH_ERROR';
export const RECOMMENDATION_FETCH_MESSAGE = 'RECOMMENDATION_FETCH_MESSAGE';
export const RECOMMENDATION_CLEAR_STATE = 'RECOMMENDATION_CLEAR_STATE';