export const ANSWERSET_FETCH_ALL = 'ANSWERSET_FETCH_ALL';
export const ANSWERSET_FETCH_SINGLE = "ANSWERSET_FETCH_SINGLE";
export const ANSWERSET_FETCH_LOADING = 'ANSWERSET_FETCH_LOADING';
export const ANSWERSET_FETCH_ERROR = 'ANSWERSET_FETCH_ERROR';
export const ANSWERSET_FETCH_MESSAGE = 'ANSWERSET_FETCH_MESSAGE';
export const ANSWERSET_CLEAR_STATE = 'ANSWERSET_CLEAR_STATE';