export const USER_FETCH_ALL = 'USER_FETCH_ALL';
export const USER_FETCH_SINGLE = "USER_FETCH_SINGLE";
export const USER_FETCH_LOADING = 'USER_FETCH_LOADING';
export const USER_FETCH_ERROR = 'USER_FETCH_ERROR';
export const USER_FETCH_MESSAGE = 'USER_FETCH_MESSAGE';
export const USER_CLEAR_STATE = 'USER_CLEAR_STATE';